// Package tables is generated by GoAdmin CLI adm.
package tables

import (
	"github.com/GoAdminGroup/go-admin/modules/db"
	"github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"
)

// Generators is a map of table models.
//
// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "menu_items" => http://localhost:9033/admin/info/menu_items
// "categories" => http://localhost:9033/admin/info/categories
// "restaurants" => http://localhost:9033/admin/info/restaurants
// "menu_item_images" => http://localhost:9033/admin/info/menu_item_images
//
// example end
var Generators = map[string]table.Generator{

	"categories":       GetCategoriesTable,
	"restaurants":      GetRestaurantsTable,
	"menu_item_images": GetMenuitemimagesTable,

	// generators end
}

// GetGenerators collects tables that require dbConn
func GetGenerators(dbConn db.Connection) table.GeneratorList {
	return table.GeneratorList{
		"menu_items": GetMenuitemsTable(dbConn),
		// Add more tables...
	}
}
